# GitHub
username: vonas
repo: https://github.com/vonas/jonasdotee.git
branch: master
github: [metadata]

# Site
url: https://jonas.ee
baseurl: /

# Page variables
email: jonasdotee@gmail.com
description: >-
  <description>
lang: en-US

exclude:
  - node_modules/
  - LICENSE.txt
  - package.json
  - yarn.lock
