# GitHub
username: vonas
repo: https://github.com/vonas/jonasdotee.git
branch: master
github: [metadata]

# Site
url: https://jonas.ee
baseurl: /

# Page
email: jonasdotee@gmail.com
description: >-
  <description>
lang: en-US
submit_action:
  development: server/submit
  production: https://jonasdotee.000webhostapp.com/submit

plugins:
  - jekyll-include-cache

exclude:
  - LICENSE.txt
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - server

include:
  - .htaccess
