# Repository information
username: vonas
repo: https://github.com/vonas/jonasdotee.git
branch: master
github: [metadata]

# Data used in pages
email: jonasdotee@gmail.com
description: >-
  <description>
lang: en-US
submit_action:
  development: server/submit
  production: https://jonasdotee.000webhostapp.com/submit

# Jekyll configuration
url: https://jonas.ee
baseurl: /

plugins:
  - jekyll-include-cache
include:
  - .htaccess
exclude:
  - LICENSE.txt
  - CNAME
  - .htaccess # FIXME: GitHub Pages doesn't support .htaccess files.
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - server
  - js/development

# TODO: Use _data files to store currencies and country-to-currency mappings.
# TODO: Use assets to compress JS, CSS and HTML.
