destination: ./build

github:
  url: https://github.com
repository: vonas/jonasdotee

lang: en-US
description: This domain is for sale.

offer:
  minimum: 20
currency:
  code: USD
  symbol: $
  description: US-Dollar (United States Dollar)
copyright:
  first_year: 2019

pageclip_url: https://send.pageclip.co
pageclip_key: iwujBjGhyRPB0WWaPC254mfexvwURcPz
pageclip_forms:
  offer: offer

simpleanalytics:
  script: https://sa.jonas.ee/app.js

libs:
  purecss:
    styles:
      - https://unpkg.com/purecss@1.0.1/build/base-min.css
      - https://unpkg.com/purecss@1.0.1/build/forms-min.css
      - https://unpkg.com/purecss@1.0.1/build/buttons-min.css
  pageclip:
    styles:
      - https://s.pageclip.co/v1/pageclip.css
    scripts:
      - https://s.pageclip.co/v1/pageclip.js

deferred_scripts: []

plugins:
  - jekyll-include-cache
  - jekyll-assets
exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - js/development
  - local

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
  endings: all
  ignore:
    envs: [ "" ] # TODO: development
  blanklines: false
  profile: false
  startings: [ html, head, body ]

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .jekyll-cache/assets
  cache_type: filesystem
  prefix: "/assets"
  assets:
    - "*.css"
    - "*.js"
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: false
    integrity: true
  external:
    uglifier:
      harmony: true
