# Repository information
username: vonas
repo: https://github.com/vonas/jonasdotee.git
branch: master
github: [metadata]

# Data used in pages
email: jonasdotee@gmail.com
description: >-
  <description>
lang: en-US
submit_action: https://jonasdotee.000webhostapp.com/submit
recaptcha_key: 6Le2KswUAAAAAMnCCeIgacnWs70BTtBV3nm6Suxy

# Jekyll configuration
url: https://jonas.ee
baseurl: /

plugins:
  - jekyll-include-cache
exclude:
  - LICENSE.txt
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - server
  - js/development
  - local

# TODO: Use _data files to store currencies and country-to-currency mappings.
# TODO: Use assets to compress JS, CSS and HTML.
