github:
  url: https://github.com
  user: vonas
  repo: jonasdotee

lang: en-US
description: This domain is for sale.

offer:
  minimum: 20
currency:
  code: USD
  symbol: $
  description: US-Dollar (United States Dollar)
copyright:
  first_year: 2019

pageclip_url: https://send.pageclip.co
pageclip_key: iwujBjGhyRPB0WWaPC254mfexvwURcPz
pageclip_forms:
  offer: offer

simpleanalytics:
  script: https://sa.jonas.ee/app.js

libs:
  purecss:
    styles:
      - https://unpkg.com/purecss@1.0.1/build/base-min.css
      - https://unpkg.com/purecss@1.0.1/build/forms-min.css
      - https://unpkg.com/purecss@1.0.1/build/buttons-min.css
  pageclip:
    styles:
      - https://s.pageclip.co/v1/pageclip.css
    scripts:
      - https://s.pageclip.co/v1/pageclip.js

deferred_scripts: []

plugins:
  - jekyll-include-cache
exclude:
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - js/development
  - local

# TODO: Jekyll: suggest exposing include file name or the like in liquid.
# TODO: Use assets to compress JS, CSS and HTML.
