#!/usr/bin/bash

case "$1 $2" in
  "bundle exec") shift; shift;;
  "bundler exec") shift; shift;;
esac

is_bundle=false
case "$1" in
  "bundle") is_bundle=true;;
  "bundler") is_bundle=true;;
esac

if [[ "$1" = "jekyll" && ("$2" = "build" || "$2" = "serve") ]]; then
  args="--incremental --config _config.yml,_config_dev.yml"
fi

if [ "$is_bundle" = false ]; then
  prefix="bundle exec"
fi

exec env $(egrep -v '^#' .env | xargs) $prefix $@ $args
