#!/usr/bin/bash

case "$1 $2" in
  "bundle exec") shift; shift;;
  "bundler exec") shift; shift;;
esac

if [[ "$1" = "jekyll" && ("$2" = "build" || "$2" = "serve") ]]; then
  args="--incremental --config _config.yml,_config_dev.yml"
fi

exec env $(egrep -v '^#' .env | xargs) bundle exec $@ $args
